version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    #command: /bin/bash
    #stdin_open: true
    #tty: true
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
