all: smart_pointer string_replace

smart_pointer: smart_pointer.cpp
	g++ -std=c++17 -g $@.cpp -o $@

string_replace: string_replace.cpp
	g++ -std=c++17 -g $@.cpp -o $@

clean:
	rm -f smart_pointer string_replace